name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"  # o "npm" se usi npm

      - name: Install dependencies
        run: yarn install  # oppure npm install

      - name: Build TypeScript
        run: yarn build    # oppure npm run build

      - name: Run tests
        run: yarn test     # oppure npm run test